-- ***************************** SqlDBM: MySQL *****************************
-- * Generated by SqlDBM: Untitled Project 2, v1 by palavras2001@gmail.com *



-- ************************************** `user`

CREATE TABLE `user`
(
 `id`         varchar(60) NOT NULL ,
 `created_at` datetime NOT NULL ,
 `updated_at` datetime NOT NULL ,
 `name`       varchar(60) NOT NULL ,
 `password`   varchar(128) NOT NULL ,

PRIMARY KEY (`id`)
);
